import { Product, Category, BlogPost, Testimonial, FAQ, FestivalCollection, CorporateGiftPackage } from "./types";

export const categories: Category[] = [
  {
    id: "almonds",
    name: "Aged Almonds",
    slug: "almonds",
    description: "Handpicked Mamra, Badam, and California Solitaires sorted for premium crunch.",
    image: "https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=600&auto=format&fit=crop&q=80",
    itemCount: 8
  },
  {
    id: "cashews",
    name: "Royal Cashews",
    slug: "cashews",
    description: "Jumbo King Cashews W180 sourced from the pristine orchards of Goa.",
    image: "https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=600&auto=format&fit=crop&q=80",
    itemCount: 7
  },
  {
    id: "pistachios",
    name: "Iranian Pistachios",
    slug: "pistachios",
    description: "Exquisite emerald-green kernels, roasted with saffron & Himalayan salt.",
    image: "https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?w=600&auto=format&fit=crop&q=80",
    itemCount: 6
  },
  {
    id: "walnuts",
    name: "Kashmiri Walnuts",
    slug: "walnuts",
    description: "Snow-white halves of exceptional oil content, directly from Kashmir.",
    image: "https://images.unsplash.com/photo-1585502766743-1e967a327ff5?w=600&auto=format&fit=crop&q=80",
    itemCount: 6
  },
  {
    id: "raisins",
    name: "Gourmet Raisins",
    slug: "raisins",
    description: "Sweet, long-seeded green raisins and luscious Afghan black currants.",
    image: "https://images.unsplash.com/photo-1534080391025-a76c6ec29a43?w=600&auto=format&fit=crop&q=80",
    itemCount: 5
  },
  {
    id: "dates",
    name: "Exquisite Dates",
    slug: "dates",
    description: "Saudi Medjool, Ajwa, and stuffed luxury dates of velvet-like texture.",
    image: "https://images.unsplash.com/photo-1501599908172-ae254ff8775a?w=600&auto=format&fit=crop&q=80",
    itemCount: 6
  },
  {
    id: "seeds",
    name: "Superfood Seeds",
    slug: "seeds",
    description: "Premium chia, sunflower, pumpkin, and roasted flax seed blends.",
    image: "https://images.unsplash.com/photo-1511149755252-35875b273fd6?w=600&auto=format&fit=crop&q=80",
    itemCount: 6
  },
  {
    id: "gift-boxes",
    name: "Luxury Gift Boxes",
    slug: "gift-boxes",
    description: "Gold-foil custom packaging with hand-poured dry fruit selections.",
    image: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&auto=format&fit=crop&q=80",
    itemCount: 6
  }
];

export const products: Product[] = [
  // --- ALMONDS (8 Products) ---
  {
    id: "alm-mamra",
    name: "Premium Kashmiri Mamra Almonds",
    category: "almonds",
    price: 2499,
    discountPrice: 2199,
    rating: 4.9,
    reviewsCount: 148,
    description: "Kashmiri Mamra Almonds are the finest almonds globally. Loaded with oil, highly nutritive, and cultivated naturally in the valleys of Kashmir without any sulfur processing.",
    benefits: ["Rich in Mono-unsaturated Fatty Acids", "Aids brain development & memory", "Improves skin radiance"],
    nutrition: { calories: "579 kcal", protein: "21.1g", carbs: "21.6g", fat: "49.9g", fiber: "12.5g" },
    image: "https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=600&auto=format&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=600&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=600&auto=format&fit=crop&q=80"
    ],
    stock: true,
    isFeatured: true,
    isBestseller: true,
    discountPercent: 12,
    sizeOptions: ["250g", "500g", "1kg"],
    tags: ["Mamra", "Kashmiri", "Organic"]
  },
  {
    id: "alm-california",
    name: "King-Size California Almonds",
    category: "almonds",
    price: 699,
    discountPrice: 599,
    rating: 4.8,
    reviewsCount: 320,
    description: "Extra large, uniformly selected California Almonds (Badam) with a buttery, sweet taste. Perfect for morning soaking routines.",
    benefits: ["Maintains heart health", "Excellent pre-workout snack", "High vitamin E content"],
    nutrition: { calories: "576 kcal", protein: "21.2g", carbs: "22.0g", fat: "49.4g", fiber: "12.2g" },
    image: "https://images.unsplash.com/photo-1511149755252-35875b273fd6?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1511149755252-35875b273fd6?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: true,
    sizeOptions: ["250g", "500g", "1kg"],
    tags: ["California", "Badam", "Raw"]
  },
  {
    id: "alm-saffron",
    name: "Saffron Infused Honeyed Almonds",
    category: "almonds",
    price: 999,
    discountPrice: 899,
    rating: 4.7,
    reviewsCount: 65,
    description: "Indulgence redefined. Premium California almonds roasted and coated in organic forest honey and Kashmiri Kesar threads.",
    benefits: ["Rich in antioxidants", "Boosts immunity & energy", "Zero artificial sweetners"],
    nutrition: { calories: "610 kcal", protein: "18.5g", carbs: "29.4g", fat: "45.1g", fiber: "10.0g" },
    image: "https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: false,
    isNew: true,
    discountPercent: 10,
    sizeOptions: ["200g", "400g"],
    tags: ["Saffron", "Honey Roasted", "Indulgence"]
  },
  {
    id: "alm-gurbandi",
    name: "Gurbandi Choti Giri Almonds",
    category: "almonds",
    price: 1199,
    discountPrice: 1099,
    rating: 4.6,
    reviewsCount: 88,
    description: "Sourced from high-altitude farms of Afghanistan, Gurbandi almonds contain a high level of natural oil and a rustic taste with an occasional bitter nut containing intense nourishment.",
    benefits: ["Highly beneficial for eyesight", "Rich in natural almond oils", "Improves overall health"],
    nutrition: { calories: "598 kcal", protein: "22.1g", carbs: "19.8g", fat: "52.3g", fiber: "11.8g" },
    image: "https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: false,
    sizeOptions: ["500g", "1kg"],
    tags: ["Gurbandi", "Afghan", "Oil-rich"]
  },
  {
    id: "alm-smoked",
    name: "Smoked Hickory Almonds",
    category: "almonds",
    price: 490,
    rating: 4.5,
    reviewsCount: 112,
    description: "Gently roasted in wood smoke and dusted with organic spices, these almonds are a perfect accompaniment to luxury cheese boards.",
    benefits: ["Perfect low-sodium savory snack", "Excellent plant protein", "Gluten-free roasted"],
    nutrition: { calories: "585 kcal", protein: "20.9g", carbs: "21.0g", fat: "48.5g", fiber: "11.9g" },
    image: "https://images.unsplash.com/photo-1511149755252-35875b273fd6?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1511149755252-35875b273fd6?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: false,
    sizeOptions: ["250g", "500g"],
    tags: ["Savory", "Smoked", "Hickory"]
  },
  {
    id: "alm-silver",
    name: "Silver-Coated Saffron Almonds",
    category: "almonds",
    price: 1599,
    discountPrice: 1399,
    rating: 4.9,
    reviewsCount: 42,
    description: "Exquisite roasted almonds infused with authentic saffron and wrapped in pure edible silver (Chandi Warq). A premium royal offering.",
    benefits: ["Authentic silver foil health benefits", "Kesar mental rejuvenation", "Royal treat"],
    nutrition: { calories: "602 kcal", protein: "19.0g", carbs: "25.0g", fat: "47.0g", fiber: "11.0g" },
    image: "https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: false,
    isNew: true,
    discountPercent: 12,
    sizeOptions: ["200g"],
    tags: ["Royal", "Silver Foil", "Saffron"]
  },
  {
    id: "alm-rose",
    name: "Damask Rose Almond Dragées",
    category: "almonds",
    price: 850,
    rating: 4.8,
    reviewsCount: 36,
    description: "Premium roasted almonds coated with real organic white chocolate and dusted with fragrant pink Damask Rose petals.",
    benefits: ["Uplifting floral aroma", "Antioxidant properties of rose", "Delicate sweet treat"],
    nutrition: { calories: "550 kcal", protein: "12.0g", carbs: "48.0g", fat: "36.0g", fiber: "7.0g" },
    image: "https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: false,
    sizeOptions: ["150g", "300g"],
    tags: ["Dragée", "Rose", "Chocolate"]
  },
  {
    id: "alm-chilli",
    name: "Tandoori Masala Roasted Almonds",
    category: "almonds",
    price: 450,
    discountPrice: 399,
    rating: 4.4,
    reviewsCount: 54,
    description: "High-grade California almonds dry-roasted with stone-ground Tandoori spices for a delightful Indian fusion flavor.",
    benefits: ["Zero trans-fats", "Boosts metabolic rates", "High fiber snack"],
    nutrition: { calories: "578 kcal", protein: "20.5g", carbs: "22.5g", fat: "48.0g", fiber: "11.5g" },
    image: "https://images.unsplash.com/photo-1511149755252-35875b273fd6?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1511149755252-35875b273fd6?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: false,
    discountPercent: 11,
    sizeOptions: ["250g", "500g"],
    tags: ["Spicy", "Tandoori", "Roasted"]
  },

  // --- CASHEWS (7 Products) ---
  {
    id: "cas-jumbo",
    name: "Royal Jumbo W180 Cashews",
    category: "cashews",
    price: 999,
    discountPrice: 899,
    rating: 4.9,
    reviewsCount: 194,
    description: "The absolute king of cashews. Huge, pristine white, curved kernels sorted under Grade W180. Handpicked from Konkan orchards for a sweet, creamy texture.",
    benefits: ["Superb source of Magnesium", "Enhances cardiovascular function", "Maintains healthy blood pressure"],
    nutrition: { calories: "553 kcal", protein: "18.2g", carbs: "30.1g", fat: "43.8g", fiber: "3.3g" },
    image: "https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=600&auto=format&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=600&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1629115916089-7e13f6492b8c?w=600&auto=format&fit=crop&q=80"
    ],
    stock: true,
    isFeatured: true,
    isBestseller: true,
    discountPercent: 10,
    sizeOptions: ["250g", "500g", "1kg"],
    tags: ["Jumbo", "W180", "Raw"]
  },
  {
    id: "cas-saffron",
    name: "Saffron Salted Roasted Cashews",
    category: "cashews",
    price: 1099,
    discountPrice: 949,
    rating: 4.8,
    reviewsCount: 122,
    description: "Exquisite W180 cashews lightly dry-roasted, infused with pure Kashmiri saffron extract and Himalayan pink salt.",
    benefits: ["Saffron elevates positive mood", "Rich mineral salt replenishment", "Delicious creamy crunch"],
    nutrition: { calories: "574 kcal", protein: "17.8g", carbs: "28.5g", fat: "45.0g", fiber: "3.0g" },
    image: "https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: true,
    discountPercent: 13,
    sizeOptions: ["250g", "500g"],
    tags: ["Saffron", "Roasted", "Salted"]
  },
  {
    id: "cas-pepper",
    name: "Black Pepper & Herb Cashews",
    category: "cashews",
    price: 550,
    rating: 4.6,
    reviewsCount: 165,
    description: "Whole cashews roasted with organic Malabar black pepper and dry rosemary leaves. A timeless, subtle-spiced crunch.",
    benefits: ["Black pepper aids digestion", "High copper content", "Perfect healthy evening snack"],
    nutrition: { calories: "560 kcal", protein: "18.0g", carbs: "29.0g", fat: "44.0g", fiber: "3.2g" },
    image: "https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: false,
    sizeOptions: ["250g", "500g"],
    tags: ["Pepper", "Herb Roasted", "Savory"]
  },
  {
    id: "cas-w240",
    name: "Premium Selection W240 Cashews",
    category: "cashews",
    price: 799,
    discountPrice: 699,
    rating: 4.7,
    reviewsCount: 110,
    description: "Standard top-tier W240 grading. Delicious, highly clean, unsalted raw cashews ideal for cooking and creating premium plant milks.",
    benefits: ["High in copper and iron", "Maintains bone strength", "Sustainably sourced"],
    nutrition: { calories: "553 kcal", protein: "18.2g", carbs: "30.1g", fat: "43.8g", fiber: "3.3g" },
    image: "https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: false,
    discountPercent: 12,
    sizeOptions: ["500g", "1kg"],
    tags: ["W240", "Raw", "Standard"]
  },
  {
    id: "cas-chilli",
    name: "Peri-Peri Zesty Cashews",
    category: "cashews",
    price: 520,
    discountPrice: 470,
    rating: 4.5,
    reviewsCount: 79,
    description: "W240 grade cashews toasted and coated in an authentic, tangy African Bird's Eye chili spice mix.",
    benefits: ["Sparks metabolism", "Tangy, non-greasy roasting", "Gluten-free"],
    nutrition: { calories: "565 kcal", protein: "17.5g", carbs: "30.5g", fat: "44.2g", fiber: "3.0g" },
    image: "https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: false,
    discountPercent: 10,
    sizeOptions: ["250g", "500g"],
    tags: ["Peri-Peri", "Spicy", "Tangy"]
  },
  {
    id: "cas-caramel",
    name: "Maple Sea-Salt Caramel Cashews",
    category: "cashews",
    price: 680,
    rating: 4.8,
    reviewsCount: 45,
    description: "Indulgently sweet cashews glazed in Canadian maple syrup, lightly caramelised with a hint of French Fleur de Sel.",
    benefits: ["Sweet energy boost", "Crafted using natural maple sugars", "High nutrient profile"],
    nutrition: { calories: "590 kcal", protein: "14.2g", carbs: "42.0g", fat: "39.0g", fiber: "2.5g" },
    image: "https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: false,
    isNew: true,
    sizeOptions: ["200g"],
    tags: ["Caramel", "Maple", "Dessert"]
  },
  {
    id: "cas-mint",
    name: "Pudina Punch Roasted Cashews",
    category: "cashews",
    price: 490,
    rating: 4.4,
    reviewsCount: 38,
    description: "Premium split and whole cashews coated with dried mint leaves and rock salt for a refreshing, cooling herbal sensation.",
    benefits: ["Mint helps relieve fatigue", "Mild and refreshing flavor", "Roasted without oil"],
    nutrition: { calories: "556 kcal", protein: "18.0g", carbs: "29.8g", fat: "43.5g", fiber: "3.4g" },
    image: "https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: false,
    sizeOptions: ["250g"],
    tags: ["Pudina", "Mint", "Cooling"]
  },

  // --- PISTACHIOS (6 Products) ---
  {
    id: "pis-salted",
    name: "Saffron Roasted Iranian Pistachios",
    category: "pistachios",
    price: 1199,
    discountPrice: 999,
    rating: 4.9,
    reviewsCount: 215,
    description: "Elite Iranian Akbari Pistachios with open shells. Slowly dry-roasted with genuine saffron threads and light salt. Incredibly rich in color and kernel size.",
    benefits: ["Superb source of Vitamin B6", "Protects eyes against blue light", "Superb snack for weight management"],
    nutrition: { calories: "562 kcal", protein: "20.3g", carbs: "27.5g", fat: "45.3g", fiber: "10.6g" },
    image: "https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?w=600&auto=format&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?w=600&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1550950158-d0d960dff51b?w=600&auto=format&fit=crop&q=80"
    ],
    stock: true,
    isFeatured: true,
    isBestseller: true,
    discountPercent: 16,
    sizeOptions: ["250g", "500g", "1kg"],
    tags: ["Akbari", "Iranian", "Saffron Roasted"]
  },
  {
    id: "pis-raw",
    name: "Emerald Green Raw Pistachio Kernels",
    category: "pistachios",
    price: 1399,
    discountPrice: 1250,
    rating: 4.8,
    reviewsCount: 92,
    description: "Shelled, skinless, premium green pistachio kernels of deep emerald intensity. Perfect for royal gourmet desserts, baklava, and pesto.",
    benefits: ["Antioxidant-dense", "Slightly sweet, fresh botanical notes", "No added sodium"],
    nutrition: { calories: "557 kcal", protein: "20.1g", carbs: "27.2g", fat: "44.4g", fiber: "10.3g" },
    image: "https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: false,
    discountPercent: 10,
    sizeOptions: ["200g", "500g"],
    tags: ["Emerald Kernels", "Shelled", "Raw"]
  },
  {
    id: "pis-lime",
    name: "Zesty Lime & Black Salt Pistachios",
    category: "pistachios",
    price: 650,
    rating: 4.7,
    reviewsCount: 88,
    description: "Jumbo open-shell Turkish pistachios roasted with real fresh lime juice and authentic Indian Kala Namak (black salt) for a tangy gourmet experience.",
    benefits: ["Electrolyte replenishing", "Deeply satisfying zesty taste", "Dry-roasted, oil-free"],
    nutrition: { calories: "569 kcal", protein: "20.0g", carbs: "28.0g", fat: "45.0g", fiber: "10.0g" },
    image: "https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: true,
    sizeOptions: ["250g", "500g"],
    tags: ["Turkish", "Lime Roasted", "Tangy"]
  },
  {
    id: "pis-chili-lemon",
    name: "Spicy Lemon-Chili Pistachios",
    category: "pistachios",
    price: 650,
    discountPrice: 590,
    rating: 4.6,
    reviewsCount: 61,
    description: "Cracked-shell giant pistachios seasoned with ground red chilies, freshly squeezed lemon, and sea salt. Packs a flavorful heat.",
    benefits: ["Capsaicin benefits", "Highly addictive, healthy replacement for chips", "Rich in fiber"],
    nutrition: { calories: "570 kcal", protein: "19.8g", carbs: "28.2g", fat: "45.1g", fiber: "10.1g" },
    image: "https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: false,
    discountPercent: 9,
    sizeOptions: ["250g", "500g"],
    tags: ["Spicy", "Lemon", "Roasted"]
  },
  {
    id: "pis-rose",
    name: "Rosemary Sea Salt Pistachios",
    category: "pistachios",
    price: 680,
    rating: 4.5,
    reviewsCount: 41,
    description: "Earthy roasted pistachios infused with fragrant farm-fresh rosemary and premium crystalline sea salt.",
    benefits: ["Herbaceous benefits", "Rich in healthy plant fats", "Wonderful snack companion"],
    nutrition: { calories: "565 kcal", protein: "20.1g", carbs: "27.8g", fat: "44.9g", fiber: "10.4g" },
    image: "https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: false,
    sizeOptions: ["250g"],
    tags: ["Rosemary", "Herbal", "Sea Salt"]
  },
  {
    id: "pis-premium-salted",
    name: "Classic Salted Akbari Pistachios",
    category: "pistachios",
    price: 1050,
    discountPrice: 899,
    rating: 4.8,
    reviewsCount: 130,
    description: "Traditional salted, open-shell Akbari pistachios. Uniformly roasted to crisp perfection, letting the natural nutty sweetness shine.",
    benefits: ["High in potassium", "Maintains clean gut flora", "Excellent crunch factor"],
    nutrition: { calories: "562 kcal", protein: "20.3g", carbs: "27.5g", fat: "45.3g", fiber: "10.6g" },
    image: "https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: false,
    discountPercent: 14,
    sizeOptions: ["250g", "500g", "1kg"],
    tags: ["Classic", "Akbari", "Salted"]
  },

  // --- WALNUTS (6 Products) ---
  {
    id: "wal-snow",
    name: "Snow-White Kashmiri Walnut Halves",
    category: "walnuts",
    price: 1299,
    discountPrice: 1099,
    rating: 4.9,
    reviewsCount: 154,
    description: "Sourced from ancient organic walnut orchards of Kashmir. These extra-light, snow-white halves represent the highest grading for Kashmiri walnuts, boasting supreme oil content.",
    benefits: ["Powerhouse of plant-based Omega-3", "Enhances brain cognitive functions", "Reduces blood inflammation"],
    nutrition: { calories: "654 kcal", protein: "15.2g", carbs: "13.7g", fat: "65.2g", fiber: "6.7g" },
    image: "https://images.unsplash.com/photo-1585502766743-1e967a327ff5?w=600&auto=format&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1585502766743-1e967a327ff5?w=600&auto=format&fit=crop&q=80"
    ],
    stock: true,
    isFeatured: true,
    isBestseller: true,
    discountPercent: 15,
    sizeOptions: ["250g", "500g", "1kg"],
    tags: ["Snow-White", "Kashmiri", "Omega-3"]
  },
  {
    id: "wal-chile",
    name: "Premium Chilean Walnut Halves",
    category: "walnuts",
    price: 999,
    discountPrice: 849,
    rating: 4.8,
    reviewsCount: 115,
    description: "Imported Chilean walnuts, celebrated globally for their uniform blonde color, buttery mild taste, and lack of bitterness. Highly sorted halves.",
    benefits: ["Extremely low in bitterness", "Maintains healthy cholesterol levels", "High oil concentration"],
    nutrition: { calories: "654 kcal", protein: "15.0g", carbs: "13.5g", fat: "65.0g", fiber: "6.5g" },
    image: "https://images.unsplash.com/photo-1585502766743-1e967a327ff5?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1585502766743-1e967a327ff5?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: true,
    discountPercent: 15,
    sizeOptions: ["250g", "500g", "1kg"],
    tags: ["Chilean", "Blonde", "Premium"]
  },
  {
    id: "wal-honey",
    name: "Honey & Cinnamon Glazed Walnuts",
    category: "walnuts",
    price: 590,
    rating: 4.7,
    reviewsCount: 53,
    description: "Gourmet Kashmiri walnuts toasted with a glaze of wild mountain honey and a dust of aromatic Sri Lankan Ceylon cinnamon.",
    benefits: ["Warm antioxidant spices", "Delicious naturally sweetened crunch", "Perfect dessert topper"],
    nutrition: { calories: "630 kcal", protein: "12.5g", carbs: "22.0g", fat: "56.0g", fiber: "6.0g" },
    image: "https://images.unsplash.com/photo-1585502766743-1e967a327ff5?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1585502766743-1e967a327ff5?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: false,
    isNew: true,
    sizeOptions: ["200g"],
    tags: ["Honey Glazed", "Cinnamon", "Gourmet"]
  },
  {
    id: "wal-inshell",
    name: "Paper-Shell Kashmiri Walnuts (In-Shell)",
    category: "walnuts",
    price: 650,
    discountPrice: 550,
    rating: 4.6,
    reviewsCount: 74,
    description: "Pure Kashmiri paper-shell walnuts. Can be easily cracked open by hand. Protects the freshness and oil integrity of the kernel within.",
    benefits: ["Maximum nutrient freshness", "Fascinating traditional cracking experience", "Chemical-free shells"],
    nutrition: { calories: "654 kcal", protein: "15.2g", carbs: "13.7g", fat: "65.2g", fiber: "6.7g" },
    image: "https://images.unsplash.com/photo-1585502766743-1e967a327ff5?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1585502766743-1e967a327ff5?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: false,
    discountPercent: 15,
    sizeOptions: ["500g", "1kg"],
    tags: ["In-Shell", "Paper-Shell", "Kashmiri"]
  },
  {
    id: "wal-amber",
    name: "Premium Amber Walnut Kernels",
    category: "walnuts",
    price: 850,
    discountPrice: 750,
    rating: 4.5,
    reviewsCount: 47,
    description: "Amber-shaded Kashmiri walnut halves and quarters. Possesses a deeper, slightly robust earthy flavor. Ideal for baking, dynamic cooking, and granola.",
    benefits: ["Deep earth-rich minerals", "High in oil", "Cost-effective premium nut"],
    nutrition: { calories: "648 kcal", protein: "15.0g", carbs: "14.0g", fat: "64.0g", fiber: "6.8g" },
    image: "https://images.unsplash.com/photo-1585502766743-1e967a327ff5?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1585502766743-1e967a327ff5?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: false,
    discountPercent: 11,
    sizeOptions: ["500g", "1kg"],
    tags: ["Amber", "Baking", "Earthy"]
  },
  {
    id: "wal-dark-chocolate",
    name: "Dark Chocolate Dusted Walnuts",
    category: "walnuts",
    price: 650,
    rating: 4.8,
    reviewsCount: 39,
    description: "Lightly roasted premium Kashmiri walnuts coated in rich 70% single-origin dark chocolate and lightly dusted with Dutch cocoa powder.",
    benefits: ["High in polyphenols", "Intense luxury cocoa experience", "Zero refined sugars"],
    nutrition: { calories: "620 kcal", protein: "13.0g", carbs: "28.0g", fat: "52.0g", fiber: "7.2g" },
    image: "https://images.unsplash.com/photo-1585502766743-1e967a327ff5?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1585502766743-1e967a327ff5?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: false,
    isNew: true,
    sizeOptions: ["200g"],
    tags: ["Chocolate Dusted", "70% Cocoa", "Indulgence"]
  },

  // --- RAISINS (5 Products) ---
  {
    id: "rai-afghan",
    name: "Royal Jumbo Green Raisins",
    category: "raisins",
    price: 499,
    discountPrice: 420,
    rating: 4.8,
    reviewsCount: 145,
    description: "Extremely long, soft-textured green raisins sourced from the sundrenched valleys of Kandahar, Afghanistan. Naturally sweet, high-energy gourmet treats.",
    benefits: ["Instant natural energy", "Helps prevent anemia", "Aids healthy digestion"],
    nutrition: { calories: "299 kcal", protein: "3.0g", carbs: "79.0g", fat: "0.5g", fiber: "3.7g" },
    image: "https://images.unsplash.com/photo-1534080391025-a76c6ec29a43?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1534080391025-a76c6ec29a43?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: true,
    discountPercent: 15,
    sizeOptions: ["250g", "500g", "1kg"],
    tags: ["Afghan", "Long-Green", "Sweets"]
  },
  {
    id: "rai-black",
    name: "Kandahar Black Raisins with Seeds",
    category: "raisins",
    price: 550,
    discountPrice: 480,
    rating: 4.9,
    reviewsCount: 110,
    description: "Authentic, dark, seed-in black grapes dried carefully under shadows. Famous in Ayurveda for blood purification and anti-aging properties.",
    benefits: ["Ayurvedic purifier", "Supports bone health", "High antioxidant resveratrol"],
    nutrition: { calories: "302 kcal", protein: "3.2g", carbs: "80.0g", fat: "0.4g", fiber: "4.0g" },
    image: "https://images.unsplash.com/photo-1534080391025-a76c6ec29a43?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1534080391025-a76c6ec29a43?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: true,
    isBestseller: true,
    discountPercent: 12,
    sizeOptions: ["250g", "500g", "1kg"],
    tags: ["Black Raisins", "Seed-in", "Ayurvedic"]
  },
  {
    id: "rai-monukka",
    name: "Abjosh Premium Afghan Monukka",
    category: "raisins",
    price: 750,
    rating: 4.7,
    reviewsCount: 65,
    description: "Large, premium black raisins boiled in milk and sun-dried according to ancestral Afghan processes. Excellent for immunity and gut health.",
    benefits: ["Incredible immune booster", "Improves hemoglobin", "High calcium content"],
    nutrition: { calories: "305 kcal", protein: "3.4g", carbs: "78.0g", fat: "0.6g", fiber: "4.2g" },
    image: "https://images.unsplash.com/photo-1534080391025-a76c6ec29a43?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1534080391025-a76c6ec29a43?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: false,
    sizeOptions: ["250g", "500g"],
    tags: ["Monukka", "Abjosh", "Immunity"]
  },
  {
    id: "rai-golden",
    name: "Sun-Dried Golden Raisins (Kishmish)",
    category: "raisins",
    price: 350,
    discountPrice: 299,
    rating: 4.5,
    reviewsCount: 180,
    description: "Sweet, tangy golden raisins processed carefully in clean facilities. Adds a magnificent bite to Indian kheer, biryanis, and festive sweets.",
    benefits: ["Tangy rich fiber snack", "Naturally high in iron", "No added sugars"],
    nutrition: { calories: "299 kcal", protein: "3.0g", carbs: "79.0g", fat: "0.5g", fiber: "3.7g" },
    image: "https://images.unsplash.com/photo-1534080391025-a76c6ec29a43?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1534080391025-a76c6ec29a43?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: false,
    discountPercent: 14,
    sizeOptions: ["500g", "1kg"],
    tags: ["Golden", "Kishmish", "Indian Sweet"]
  },
  {
    id: "rai-black-seedless",
    name: "Premium Seedless Black Currants",
    category: "raisins",
    price: 490,
    rating: 4.6,
    reviewsCount: 55,
    description: "Imported seedless black currants dried under optimal hygiene conditions. Tangy and intensely grapey, ideal for oats and breakfast yogurts.",
    benefits: ["Rich in anthocyanins", "High vitamin C trace", "Extremely low calorie bite"],
    nutrition: { calories: "283 kcal", protein: "2.8g", carbs: "74.0g", fat: "0.3g", fiber: "4.5g" },
    image: "https://images.unsplash.com/photo-1534080391025-a76c6ec29a43?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1534080391025-a76c6ec29a43?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: false,
    sizeOptions: ["250g", "500g"],
    tags: ["Currants", "Black Grapes", "Seedless"]
  },

  // --- DATES (6 Products) ---
  {
    id: "dat-medjool",
    name: "Luxury Saudi Medjool Dates",
    category: "dates",
    price: 1599,
    discountPrice: 1350,
    rating: 4.9,
    reviewsCount: 220,
    description: "Celebrated as the King of Dates. These organic Saudi Medjool dates are extremely large, incredibly moist, and possess a sweet caramel-like flavor and a melt-in-the-mouth texture.",
    benefits: ["High in potassium & potassium minerals", "Perfect sugar-substitute sweetener", "Rich in digestible fibers"],
    nutrition: { calories: "277 kcal", protein: "1.8g", carbs: "75.0g", fat: "0.2g", fiber: "6.7g" },
    image: "https://images.unsplash.com/photo-1501599908172-ae254ff8775a?w=600&auto=format&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1501599908172-ae254ff8775a?w=600&auto=format&fit=crop&q=80"
    ],
    stock: true,
    isFeatured: true,
    isBestseller: true,
    discountPercent: 15,
    sizeOptions: ["500g", "1kg"],
    tags: ["Medjool", "Saudi", "Caramel-taste"]
  },
  {
    id: "dat-ajwa",
    name: "Al-Madinah Royal Ajwa Dates",
    category: "dates",
    price: 1899,
    discountPrice: 1690,
    rating: 5.0,
    reviewsCount: 180,
    description: "Sourced directly from holy farms of Al-Madinah. Small, soft, extremely dark black dates with a highly revered heritage and distinct fine texture.",
    benefits: ["Sought for active heart health", "Ayurvedic and Islamic traditional healing", "Intense mineral profile"],
    nutrition: { calories: "282 kcal", protein: "2.0g", carbs: "74.0g", fat: "0.2g", fiber: "7.0g" },
    image: "https://images.unsplash.com/photo-1501599908172-ae254ff8775a?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1501599908172-ae254ff8775a?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: true,
    discountPercent: 11,
    sizeOptions: ["400g", "800g"],
    tags: ["Ajwa", "Madinah", "Sacred"]
  },
  {
    id: "dat-safawi",
    name: "Soft Premium Safawi Dates",
    category: "dates",
    price: 799,
    discountPrice: 699,
    rating: 4.7,
    reviewsCount: 94,
    description: "Safawi dates are dark brown, elongated, and intensely sweet. Known for their chewiness and deep-toned dates energy.",
    benefits: ["Supports gut motility", "Zero cholesterol and sodium", "Excellent quick workout fuel"],
    nutrition: { calories: "275 kcal", protein: "1.9g", carbs: "74.5g", fat: "0.1g", fiber: "6.5g" },
    image: "https://images.unsplash.com/photo-1501599908172-ae254ff8775a?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1501599908172-ae254ff8775a?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: false,
    discountPercent: 12,
    sizeOptions: ["500g", "1kg"],
    tags: ["Safawi", "Soft", "Everyday Energy"]
  },
  {
    id: "dat-kalmi",
    name: "Classic Kalmi Dates",
    category: "dates",
    price: 650,
    rating: 4.6,
    reviewsCount: 112,
    description: "Cultivated in Saudi deserts, Kalmi dates have a soft exterior and a rich dense flavor. Packed with active nutrition.",
    benefits: ["High copper trace", "Excellent texture for shakes", "Natural sweetener"],
    nutrition: { calories: "276 kcal", protein: "1.8g", carbs: "75.0g", fat: "0.1g", fiber: "6.8g" },
    image: "https://images.unsplash.com/photo-1501599908172-ae254ff8775a?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1501599908172-ae254ff8775a?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: false,
    sizeOptions: ["500g", "1kg"],
    tags: ["Kalmi", "Everyday", "Natural Sweetener"]
  },
  {
    id: "dat-stuffed-almond",
    name: "Almond Stuffed Medjool Dates",
    category: "dates",
    price: 1250,
    discountPrice: 1100,
    rating: 4.9,
    reviewsCount: 48,
    description: "Premium selection Medjool dates, de-seeded and stuffed with crunchy roasted California solitaire almonds. A sweet, nut-filled treat.",
    benefits: ["Balanced sugars and plant protein", "Delightful high-class snack combo", "Zero artificial syrups"],
    nutrition: { calories: "380 kcal", protein: "5.5g", carbs: "54.0g", fat: "14.0g", fiber: "8.2g" },
    image: "https://images.unsplash.com/photo-1501599908172-ae254ff8775a?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1501599908172-ae254ff8775a?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: false,
    isNew: true,
    discountPercent: 12,
    sizeOptions: ["250g", "500g"],
    tags: ["Stuffed", "Almond filled", "Gourmet Gift"]
  },
  {
    id: "dat-chocolate",
    name: "Gourmet Dark Chocolate Coated Dates",
    category: "dates",
    price: 990,
    rating: 4.8,
    reviewsCount: 37,
    description: "Premium chewy dates filled with salted cashews, dipped in rich 60% dark chocolate. Pure artisan dessert perfection.",
    benefits: ["Luxury chocolate indulgence", "Antioxidant rich cocoa", "No processed sugar additives"],
    nutrition: { calories: "410 kcal", protein: "4.5g", carbs: "58.0g", fat: "16.5g", fiber: "7.0g" },
    image: "https://images.unsplash.com/photo-1501599908172-ae254ff8775a?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1501599908172-ae254ff8775a?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: false,
    sizeOptions: ["200g"],
    tags: ["Chocolate coated", "Dessert", "Stuffed"]
  },

  // --- SEEDS (6 Products) ---
  {
    id: "see-pumpkin",
    name: "Roasted Himalayan Saffron Pumpkin Seeds",
    category: "seeds",
    price: 490,
    discountPrice: 420,
    rating: 4.7,
    reviewsCount: 112,
    description: "Organic green pumpkin seed kernels (Magaj) roasted lightly and infused with real Kashmiri saffron threads and sea salt. Crisp and highly nutritive.",
    benefits: ["Rich in Zinc for immune health", "Excellent natural source of tryptophan", "Boosts metabolic strength"],
    nutrition: { calories: "559 kcal", protein: "30.2g", carbs: "10.7g", fat: "49.0g", fiber: "6.0g" },
    image: "https://images.unsplash.com/photo-1511149755252-35875b273fd6?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1511149755252-35875b273fd6?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: true,
    discountPercent: 14,
    sizeOptions: ["250g", "500g"],
    tags: ["Pumpkin Seeds", "Saffron Roasted", "Zinc"]
  },
  {
    id: "see-chia",
    name: "Premium Peruvian Black Chia Seeds",
    category: "seeds",
    price: 390,
    rating: 4.8,
    reviewsCount: 140,
    description: "Sourced from native organic farms in Peru. Absorbs water rapidly to form high-fiber gel. Extremely rich in calcium and omega fatty acids.",
    benefits: ["High fiber gut booster", "Superb vegan omega-3 source", "Promotes long-lasting hydration"],
    nutrition: { calories: "486 kcal", protein: "16.5g", carbs: "42.1g", fat: "30.7g", fiber: "34.4g" },
    image: "https://images.unsplash.com/photo-1511149755252-35875b273fd6?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1511149755252-35875b273fd6?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: false,
    sizeOptions: ["250g", "500g"],
    tags: ["Chia", "Raw", "Superfood"]
  },
  {
    id: "see-sunflower",
    name: "Gently Roasted Sunflower Seeds",
    category: "seeds",
    price: 350,
    discountPrice: 299,
    rating: 4.5,
    reviewsCount: 78,
    description: "Peeled sunflower kernels dry-roasted without oils. High in Vitamin E, these nutty-flavored seeds are a magnificent crunch on salads.",
    benefits: ["Very high in Vitamin E", "Maintains skin elasticity", "Heart health support"],
    nutrition: { calories: "584 kcal", protein: "20.8g", carbs: "20.0g", fat: "51.5g", fiber: "8.6g" },
    image: "https://images.unsplash.com/photo-1511149755252-35875b273fd6?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1511149755252-35875b273fd6?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: false,
    discountPercent: 14,
    sizeOptions: ["250g", "500g"],
    tags: ["Sunflower", "Roasted", "Vitamin E"]
  },
  {
    id: "see-flax",
    name: "Roasted Crunchy Brown Flax Seeds",
    category: "seeds",
    price: 250,
    rating: 4.6,
    reviewsCount: 98,
    description: "Slow-roasted brown flax seeds (Alsi) that release an intense nutty flavor. Perfect digestive seed eaten post meals.",
    benefits: ["Rich in active plant lignans", "Improves daily digestion", "Soluble fiber source"],
    nutrition: { calories: "534 kcal", protein: "18.3g", carbs: "28.9g", fat: "42.2g", fiber: "27.3g" },
    image: "https://images.unsplash.com/photo-1511149755252-35875b273fd6?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1511149755252-35875b273fd6?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: false,
    sizeOptions: ["250g", "500g"],
    tags: ["Flax Seeds", "Alsi", "Post-meal Digest"]
  },
  {
    id: "see-watermelon",
    name: "Roasted Spicy Watermelon Kernels",
    category: "seeds",
    price: 320,
    discountPrice: 280,
    rating: 4.4,
    reviewsCount: 42,
    description: "Raw shelled watermelon kernels dry-roasted with black salt, dry mango powder, and a dash of hot chili.",
    benefits: ["High biological value protein", "Improves heart stamina", "Spicy tasty low-carb crunch"],
    nutrition: { calories: "557 kcal", protein: "28.3g", carbs: "15.0g", fat: "47.0g", fiber: "5.5g" },
    image: "https://images.unsplash.com/photo-1511149755252-35875b273fd6?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1511149755252-35875b273fd6?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: false,
    discountPercent: 12,
    sizeOptions: ["250g"],
    tags: ["Watermelon Seeds", "Spicy", "High Protein"]
  },
  {
    id: "see-mix-7",
    name: "7-in-1 Premium Roasted Superseed Mix",
    category: "seeds",
    price: 499,
    discountPrice: 449,
    rating: 4.9,
    reviewsCount: 165,
    description: "The ultimate wellness mix containing roasted pumpkin, sunflower, flax, chia, sesame, watermelon, and muskmelon seeds, lightly tossed in mineral pink salt.",
    benefits: ["Complete multi-seed nutrition", "Extremely rich in trace minerals", "Zero oils used"],
    nutrition: { calories: "525 kcal", protein: "22.5g", carbs: "21.0g", fat: "41.5g", fiber: "14.0g" },
    image: "https://images.unsplash.com/photo-1511149755252-35875b273fd6?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1511149755252-35875b273fd6?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: true,
    isBestseller: true,
    discountPercent: 10,
    sizeOptions: ["250g", "500g"],
    tags: ["Seed Mix", "Superseed", "7-in-1"]
  },

  // --- LUXURY GIFT BOXES (11 Products) ---
  {
    id: "gb-royal-gold",
    name: "The Royal Gold Sovereign Hamper",
    category: "gift-boxes",
    price: 3499,
    discountPrice: 2999,
    rating: 5.0,
    reviewsCount: 140,
    description: "A breathtaking velvet-lined wooden chest wrapped in custom gold foil, containing 4 modular glass jars of Saffron Mamra Almonds, W180 Jumbo Cashews, Salted Akbari Pistachios, and Royal Medjool Dates.",
    benefits: ["Stunning luxury premium presentation", "Free custom hand-written greeting card", "Acoustic gold-latch magnetic chest"],
    nutrition: { calories: "Varies", protein: "Varies", carbs: "Varies", fat: "Varies", fiber: "Varies" },
    image: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&auto=format&fit=crop&q=80",
    gallery: [
      "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1513201099705-a9746e1e201f?w=600&auto=format&fit=crop&q=80"
    ],
    stock: true,
    isFeatured: true,
    isBestseller: true,
    discountPercent: 14,
    sizeOptions: ["Large Assortment"],
    tags: ["Gift Box", "Sovereign Hamper", "Velvet Chest"]
  },
  {
    id: "gb-festive-shubh",
    name: "The 'Shubh Agaman' Festive Box",
    category: "gift-boxes",
    price: 2499,
    discountPrice: 1999,
    rating: 4.9,
    reviewsCount: 88,
    description: "A beautifully hand-painted traditional Mandala circular box, filled with Premium Kashmiri Walnut Halves, Jumbo California Almonds, Royal Cashews, and Iranian Pistachios.",
    benefits: ["Handmade artisanal box design", "Perfect for Diwali & Rakhi gifting", "Hermetically vacuum-sealed nuts"],
    nutrition: { calories: "Varies", protein: "Varies", carbs: "Varies", fat: "Varies", fiber: "Varies" },
    image: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: true,
    discountPercent: 20,
    sizeOptions: ["Standard Assortment"],
    tags: ["Festive Box", "Mandala Box", "Handmade"]
  },
  {
    id: "gb-corporate-class",
    name: "The 'Elegance' Corporate Gift Box",
    category: "gift-boxes",
    price: 1850,
    discountPrice: 1599,
    rating: 4.8,
    reviewsCount: 205,
    description: "Sleek, minimalist matte charcoal drawer-slider box designed for modern offices. Includes premium roasted almonds, salt & pepper cashews, and a wellness seed blend.",
    benefits: ["Customisable logo print on demand", "Understated modern design aesthetic", "Eco-friendly fully recyclable casing"],
    nutrition: { calories: "Varies", protein: "Varies", carbs: "Varies", fat: "Varies", fiber: "Varies" },
    image: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: true,
    discountPercent: 13,
    sizeOptions: ["Classic Collection"],
    tags: ["Corporate", "Modern Box", "Eco"]
  },
  {
    id: "gb-kesar-jugalbandi",
    name: "Saffron & Mamra Jugalbandi Pack",
    category: "gift-boxes",
    price: 2999,
    rating: 4.9,
    reviewsCount: 34,
    description: "An elegant duo: 1 jar containing 200g of natural Kashmiri Mamra Almonds and 1 vintage jar holding 2g of high-potency pure Kashmiri Saffron Threads.",
    benefits: ["Highest grade Kesar included", "Luxury organic wellness focus", "Perfect for premium wedding invites"],
    nutrition: { calories: "Varies", protein: "Varies", carbs: "Varies", fat: "Varies", fiber: "Varies" },
    image: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: false,
    isNew: true,
    sizeOptions: ["Dual Luxury Jar Set"],
    tags: ["Saffron Duo", "Mamra", "Wedding Invite"]
  },
  {
    id: "gb-imperial-tray",
    name: "The Imperial Hand-Carved Brass Tray",
    category: "gift-boxes",
    price: 4500,
    discountPrice: 3999,
    rating: 5.0,
    reviewsCount: 22,
    description: "A genuine, heavy hand-beaten Moradabad brass serving tray, pre-arranged with luxury partitions containing Premium Iranian Pistachios, King Cashews, Kashmiri Walnuts, and Stuffed Medjool Dates.",
    benefits: ["Heirloom brass tray keeps forever", "Ultra-luxury premium masterpiece", "Stunning centerpiece for royal parties"],
    nutrition: { calories: "Varies", protein: "Varies", carbs: "Varies", fat: "Varies", fiber: "Varies" },
    image: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: false,
    discountPercent: 11,
    sizeOptions: ["Brass Tray Arranged"],
    tags: ["Brass Tray", "Artisanal", "Heirloom"]
  },
  {
    id: "gb-sweet-delight",
    name: "Indulgent Dragée & Chocolate Hamper",
    category: "gift-boxes",
    price: 1999,
    rating: 4.7,
    reviewsCount: 46,
    description: "A colorful, vibrant slider box presenting Rose Petal Almond Dragées, Saffron White Cashews, Dark Cocoa Walnuts, and Maple Almonds.",
    benefits: ["Perfect sweet tooth replacement", "Highly aesthetic color-pop candy jars", "Unique luxury flavors"],
    nutrition: { calories: "Varies", protein: "Varies", carbs: "Varies", fat: "Varies", fiber: "Varies" },
    image: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&auto=format&fit=crop&q=80",
    gallery: ["https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&auto=format&fit=crop&q=80"],
    stock: true,
    isFeatured: false,
    sizeOptions: ["Assorted Sweet Collection"],
    tags: ["Dragées", "Chocolates", "Hamper"]
  }
];

export const blogs: BlogPost[] = Array.from({ length: 20 }, (_, i) => {
  const titles = [
    "The Health Secrets of Kashmiri Mamra Almonds",
    "Why grading matters: Understanding Cashew sizes W180 to W240",
    "The Golden Spice: Sourcing Authentic Kashmiri Saffron",
    "Omega-3 powerhouses: Why Kashmiri walnuts beat the rest",
    "Ayurvedic benefits of eating soaked Almonds and Dates daily",
    "How to spot synthetic chemical processing in dry fruits",
    "The perfect curated gift box: Etiquette for Indian weddings",
    "Top 5 high-oil seeds you must add to your morning oats",
    "The desert medicine: Nutritional overview of Royal Ajwa Dates",
    "From Iran with Love: The exquisite taste of Akbari Pistachios",
    "Sustainable direct-sourcing: Empowering farmers in Kashmir",
    "Healthy snacks: Ditching fried chips for roasted dry fruits",
    "Why organic Mamra almonds are worth every rupee",
    "The science of vacuum-sealed fresh storage for premium nuts",
    "Perfect Diwali gifts: Elevate your relationships with luxury dry fruits",
    "How dry fruits can naturally boost skin collagen and glow",
    "A guide to baking the ultimate premium walnut brownie",
    "Pre-workout superfoods: Natural athletic fuel from dates & almonds",
    "Black raisins vs Green raisins: A complete comparison of benefits",
    "Unboxing Luxury: Inside the design of our velvet-lined gift boxes"
  ];

  const categoriesList = ["Nutrition", "Sourcing", "Lifestyle", "Recipes", "Gifting"];

  return {
    id: `blog-${i + 1}`,
    title: titles[i],
    summary: `Discover the exquisite culinary details, botanical backgrounds, and clinical health benefits associated with world-class dry fruits. In this detailed exploration, we guide you through professional sourcing secrets.`,
    content: `## Introduction\n\nWhen we talk about premium wellness, our minds naturally drift to standard choices like greens and grains. However, the true gold standard of ancient nutrition sits in a humbler basket: hand-harvested premium dry fruits. From the mineral-rich, high-altitude orchards of Kashmir to the sun-soaked valleys of Iranian desert regions, these gourmet food sources possess incredibly concentrated nutrition.\n\n### Why Quality Matters\n\nNot all almonds are created equal. For instance, **Kashmiri Mamra Almonds** are cultivated entirely naturally under organic mountain climates. They are noticeably smaller and slightly twisted, yet they pack over double the oil content of a standard, industrial California flat almond. This natural almond oil contains rich reserves of Vitamin E, mono-unsaturated fatty acids, and essential trace minerals.\n\nSimilarly, grading systems like **W180 Jumbo Cashews** represent the peak size of whole cashews. In dry fruit commerce, W stands for 'White Whole' and 180 denotes the number of kernels per pound. A W180 is extremely rare, delivering a luscious, milky sweetness that standard split cashews simply cannot match.\n\n### Incorporating Dry Fruits into Daily Routine\n\nAyurveda recommends soaking almonds overnight to neutralize phytic acids present in the brown skin, making them incredibly easy to digest and unlock bioavailability. Combining 4 soaked Mamra almonds with 2 Royal Ajwa dates each morning provides an instant, stable energy release that supports cognitive longevity and heart vitality.\n\n### Conclusion\n\nWhen you invest in Star Dry Fruits, you are not just purchasing a snack; you are bringing home centuries of horticultural heritage and clean, pesticide-free, natural medicine. Elevate your everyday nutrition to royal status.`,
    category: categoriesList[i % categoriesList.length],
    date: new Date(2026, 5, 20 - i).toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" }),
    author: i % 2 === 0 ? "Dr. Meera Sen (Nutritionist)" : "Nikhil Sharma (Sourcing Lead)",
    image: [
      "https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1608039829572-78524f79c4c7?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?w=800&auto=format&fit=crop&q=80"
    ][i % 3],
    readTime: `${4 + (i % 3)} min read`,
    views: 120 + i * 45,
    likes: 34 + i * 12,
    tags: ["DryFruits", "Wellness", "Organic", "LuxuryGifting"]
  };
});

export const testimonials: Testimonial[] = [
  {
    id: "test-1",
    name: "Aishwarya Rai-Bachchan",
    role: "Gourmet Connoisseur",
    company: "Mumbai",
    comment: "The Kashmiri Mamra almonds from Star Dry Fruits are unlike anything I have ever bought. They are loaded with rich oils, exceptionally crunchy, and packaged beautifully. Truly a ₹50+ lakh experience!",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80",
    isFeatured: true
  },
  {
    id: "test-2",
    name: "Aditya Birla",
    role: "VP Corporate Procurement",
    company: "Aditya Birla Group",
    comment: "We ordered 1,500 of the Custom Velvet Chests for our corporate leadership team during Diwali. The feedback was outstanding. The direct-sourcing quality and gold foil presentation are unmatched in India.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80",
    isFeatured: true
  },
  {
    id: "test-3",
    name: "Chef Kunal Kapur",
    role: "Celebrity Masterchef",
    company: "New Delhi",
    comment: "As a professional chef, the culinary purity of raw ingredients is everything. Their emerald green raw pistachios and Kashmiri walnut halves possess exceptional freshness, completely devoid of any rancid taste.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80",
    isFeatured: true
  },
  {
    id: "test-4",
    name: "Priyanka Chopra",
    role: "Lifestyle Blogger",
    company: "Vogue India",
    comment: "Star Dry Fruits has successfully transformed dry fruits from standard groceries into absolute high-end lifestyle items. The Rose Petal Almond Dragées are heavenly!",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80",
    isFeatured: false
  },
  {
    id: "test-5",
    name: "Rohan Malhotra",
    role: "Fitness Coach",
    company: "Cult.Fit",
    comment: "My clients look for raw, high-potency superfoods. The 7-in-1 seed mix and Medjool dates from Star are standard dietary recommendations in my routines now.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&auto=format&fit=crop&q=80",
    isFeatured: false
  },
  {
    id: "test-6",
    name: "Devika Narain",
    role: "Premium Wedding Designer",
    company: "Devika Narain & Co",
    comment: "The heavy hand-beaten Moradabad brass trays pre-arranged with gold jars were the highlight of our Jaipur luxury wedding invites. Truly regal.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80",
    isFeatured: true
  },
  {
    id: "test-7",
    name: "Vikram Chandra",
    role: "Tech Entrepreneur",
    company: "Bengaluru",
    comment: "Extremely seamless online presentation. If the final shopify site matches this level of premium user interface, it will set a new global benchmark.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=120&auto=format&fit=crop&q=80",
    isFeatured: false
  },
  {
    id: "test-8",
    name: "Shalini Naidu",
    role: "Daily Homemaker",
    company: "Chennai",
    comment: "I used to buy dry fruits from local shops, but the freshness was always inconsistent. Star Dry Fruits is worth every penny—every single nut is perfect.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80",
    isFeatured: false
  },
  {
    id: "test-9",
    name: "Anand Mahindra",
    role: "Luxury Aficionado",
    company: "Mumbai",
    comment: "Superb attention to detail on the packaging. The corporate gift boxes look incredibly professional and proudly convey 'Made in India' luxury.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80",
    isFeatured: true
  },
  {
    id: "test-10",
    name: "Mira Rajput-Kapoor",
    role: "Wellness Advocate",
    company: "Mumbai",
    comment: "Ajwa and Medjool dates from Star are soft, caramelised, and completely natural. They make the perfect sugar-free dessert for my kids.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80",
    isFeatured: false
  },
  {
    id: "test-11",
    name: "Karan Johar",
    role: "Film Producer",
    company: "Dharma Productions",
    comment: "When it comes to luxury hampers for my film launches, only Star Dry Fruits makes the cut. The gold sovereign hampers are cinematic perfection.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&auto=format&fit=crop&q=80",
    isFeatured: false
  },
  {
    id: "test-12",
    name: "Nita Ambani",
    role: "Philanthropist & Chairperson",
    company: "Reliance Foundation",
    comment: "The hand-painted circular Mandala boxes we commissioned for our cultural guests were stunning works of Indian art. World-class quality.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=120&auto=format&fit=crop&q=80",
    isFeatured: true
  }
];

export const faqs: FAQ[] = [
  {
    id: "faq-1",
    question: "What makes Kashmiri Mamra Almonds different from regular almonds?",
    answer: "Mamra almonds are grown naturally in cold mountain climates without chemical insecticides. They are smaller and concave, but pack more than double the organic oil concentration of regular flat California almonds, rendering supreme benefits for brain health, skin luster, and energy.",
    category: "Products"
  },
  {
    id: "faq-2",
    question: "Do you use sulfur or chemical preservatives to make raisins and nuts look brighter?",
    answer: "Absolutely not. Star Dry Fruits is committed to complete botanical purity. Our premium nuts and raisins are dried using traditional natural shadow drying and sun-drying processes, entirely free from sulfur fumigation, synthetic wax, or mineral oil coatings.",
    category: "Purity"
  },
  {
    id: "faq-3",
    question: "How should I store my dry fruits to maintain absolute freshness?",
    answer: "Since our premium products have no chemical preservatives, we highly recommend storing them in cool, dry places, preferably in airtight glass jars inside your refrigerator. Avoid exposure to hot humid air and direct sunlight to protect the natural oils from oxidation.",
    category: "Storage"
  },
  {
    id: "faq-4",
    question: "Can we customize corporate gift boxes with our own company branding?",
    answer: "Yes, we specialize in luxury corporate customization. For bulk orders exceeding 50 hampers, we can engrave your logo on our wood-crafted boxes, print custom sleeve wraps, and include hand-poured custom assortment ratios to match your budget and brand.",
    category: "Gifting"
  },
  {
    id: "faq-5",
    question: "Where do you source your jumbo cashews from?",
    answer: "Our jumbo grade cashews are sourced directly from sustainable farmers in the coastal Konkan belt and Goa. Each cashew is physically verified to ensure it meets grade W180 (the largest size worldwide, meaning only 180 whole cashews make up one pound).",
    category: "Sourcing"
  },
  {
    id: "faq-6",
    question: "Are your gift boxes completely eco-friendly?",
    answer: "We offer dual lines of premium packaging. Our wooden boxes are crafted from sustainably harvested walnut wood, which can be reused as heirloom organizers. Our paper slider boxes are made from 100% recycled high-thickness post-consumer pulp printed with soy-based organic inks.",
    category: "Sustainability"
  },
  {
    id: "faq-7",
    question: "What is your standard shipping timeline across premium Indian metros?",
    answer: "We ship all orders via premium express air couriers. For tier-1 metro cities (Mumbai, New Delhi, Bengaluru, Chennai), delivery is fulfilled within 24 to 48 hours. Other cities receive delivery within 3 to 5 business days.",
    category: "Shipping"
  },
  {
    id: "faq-8",
    question: "Are dry fruit seed combinations suitable for raw vegan diets?",
    answer: "Yes, all our seed blends and raw nut lines (except chocolate-coated dragées containing dairy traces) are 100% raw, vegan-friendly, non-GMO, and gluten-free, serving as outstanding sources of clean, healthy plant protein.",
    category: "Products"
  },
  {
    id: "faq-9",
    question: "What are the payment options for bulk corporate inquiries?",
    answer: "For presentation demos, we support simple quotation inquiries. Real corporate billing is processed via NEFT/RTGS bank transfers, corporate cards, and standard GST-compliant tax invoicing structures upon proof-of-concept approval.",
    category: "Gifting"
  },
  {
    id: "faq-10",
    question: "Do you offer international shipping?",
    answer: "Yes, we facilitate international shipping to over 45 countries including the USA, UK, UAE, and Singapore, complying with all necessary USDA, FDA, and customs clearance health certifications.",
    category: "Shipping"
  }
];

export const festivalCollections: FestivalCollection[] = [
  {
    id: "fest-diwali",
    name: "The Royal Diwali Durbar",
    description: "Gold-embossed chests packed with classic saffron nuts, dry fruit rolls, and premium silver dragées for India's grandest festival.",
    image: "https://images.unsplash.com/photo-1513201099705-a9746e1e201f?w=600&auto=format&fit=crop&q=80",
    themeColor: "from-amber-600 to-amber-950",
    slug: "diwali"
  },
  {
    id: "fest-rakhi",
    name: "Raksha Bandhan Sovereign Ties",
    description: "Elegant silk-woven hampers combining luxury walnut halves and roasted salted cashew nut jars with designer silver Rakhis.",
    image: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&auto=format&fit=crop&q=80",
    themeColor: "from-pink-700 to-pink-950",
    slug: "raksha-bandhan"
  },
  {
    id: "fest-wedding",
    name: "Imperial Shadi Milap Invitations",
    description: "Solid Moradabad brass trays arranged beautifully with premium dates and rose almond dragées designed for royal wedding invites.",
    image: "https://images.unsplash.com/photo-1511149755252-35875b273fd6?w=600&auto=format&fit=crop&q=80",
    themeColor: "from-yellow-700 to-yellow-950",
    slug: "wedding-gifts"
  },
  {
    id: "fest-corporate",
    name: "Executive Leadership Hampers",
    description: "Sleek matte-charcoal desk drawers with healthy custom seed mixes and organic Kashmiri almond jars for luxury corporate milestones.",
    image: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&auto=format&fit=crop&q=80",
    themeColor: "from-slate-700 to-slate-950",
    slug: "corporate-gifts"
  },
  {
    id: "fest-birthday",
    name: "Luxury Milestone Birthday Hampers",
    description: "Delicate pastel-toned boxes packed with honey-coated cashews, chocolate dates, and customized greeting templates.",
    image: "https://images.unsplash.com/photo-1513201099705-a9746e1e201f?w=600&auto=format&fit=crop&q=80",
    themeColor: "from-rose-600 to-rose-950",
    slug: "birthday-hampers"
  },
  {
    id: "fest-eid",
    name: "The Blessed Eid Crescent Collection",
    description: "Beautiful crescent-themed boxes showcasing Al-Madinah Ajwa dates, stuffed Medjool dates, and premium Iranian salted pistachios.",
    image: "https://images.unsplash.com/photo-1501599908172-ae254ff8775a?w=600&auto=format&fit=crop&q=80",
    themeColor: "from-emerald-700 to-emerald-950",
    slug: "eid"
  }
];

export const corporateGiftPackages: CorporateGiftPackage[] = [
  {
    id: "corp-bronze",
    name: "The Sovereign Desk-Tray Collection",
    priceRange: "₹850 - ₹1,200 per box",
    description: "Designed for modern desktop placement. An organic fiber eco-friendly tray housing roasted California almonds, premium black raisins, and our signature 7-in-1 superseed mix.",
    contents: ["Roasted California Almonds (150g)", "Premium Sundried Green Raisins (150g)", "7-in-1 Superseed wellness mix (150g)", "Custom branded executive sleeve packaging"],
    minQuantity: 100,
    image: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "corp-silver",
    name: "The Mahogany Classic Drawer Set",
    priceRange: "₹1,800 - ₹2,500 per chest",
    description: "A premium walnut wood drawer-slider box filled with high-end culinary selection: Saffron salt-roasted cashews, jumbo green raisins, raw walnut halves, and classic roasted salted pistachios.",
    contents: ["Saffron Salt-Roasted Cashews (200g)", "Sun-Dried Royal Green Raisins (200g)", "Light Kashmiri Walnut Halves (150g)", "Classic Salted Akbari Pistachios (200g)", "Laser-engraved custom brand plaque on wood chest"],
    minQuantity: 50,
    image: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&auto=format&fit=crop&q=80"
  },
  {
    id: "corp-gold",
    name: "The Vice-Presidential Signature Trunk",
    priceRange: "₹3,500 - ₹5,000 per trunk",
    description: "The peak of executive gifting. A lush velvet-lined leatherette gold-embossed trunk housing our most elite collection: Saffron Mamra almonds, stuffed royal Medjool dates, gold-dusted Cashew halves, and raw green pistachios.",
    contents: ["Kashmiri Mamra Almonds (250g)", "Almond Stuffed Medjool Dates (250g)", "Saffron Roasted Akbari Pistachios (250g)", "Moradabad hand-beaten brass tea lights", "Premium hand-signed parchment greeting scroll"],
    minQuantity: 20,
    image: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=600&auto=format&fit=crop&q=80"
  }
];
